### ISSUE TITLE
Sadly did not pass the "Shrek test"

### ISSUE THREAD

**Issue by ggtylerr** [EladKarni/limbo-encoder#1]
### Issue Description
When attempting to compress a video with a large file size (in this case, Shrek), the software fails to compress it.

### Reproduction steps:
1. Get a **_legal_** copy of a movie _(I used Shrek cause of memes and [there's a copy on the Internet Archive.](https://archive.org/details/acmima-Shrek_The_Musical) For testing purposes, used H.264 since it's the largest file size.)_
2. Upload it and attempt to compress (for best results, select 8MB.)
3. Disappointment

### Extra details
* This was tested on a local copy, since I don't trust my ISP to not flag the upload as piracy. 
* Viewing the console reveals [this log.](https://hastebin.com/bariyihulo.yaml)

### Additional notes
I don't intend to commit piracy and I was mainly trying to do this for shits and giggles. I'm just a bit upset that I'm not able to do something absolutely absurd.

**Comment by Micah-L18** [comment]
didnt pass the "sportsball test" #1 as well

**Comment by EladKarni** [comment]
This is going to be my top priority!

**Comment by Micah-L18** [comment]
Thank you kind sir

**Comment by EladKarni** [comment]
> ### Issue Description
> When attempting to compress a video with a large file size (in this case, Shrek), the software fails to compress it.
> 
> ### Reproduction steps:
> 1. Get a **_legal_** copy of a movie _(I used Shrek cause of memes and [there's a copy on the Internet Archive.](https://archive.org/details/acmima-Shrek_The_Musical) For testing purposes, used H.264 since it's the largest file size.)_
> 2. Upload it and attempt to compress (for best results, select 8MB.)
> 3. Disappointment
> 
> ### Extra details
> * This was tested on a local copy, since I don't trust my ISP to not flag the upload as piracy.
> * Viewing the console reveals [this log.](https://hastebin.com/bariyihulo.yaml)
> 
> ### Additional notes
> I don't intend to commit piracy and I was mainly trying to do this for shits and giggles. I'm just a bit upset that I'm not able to do something absolutely absurd.

Seems like this is a limitation of the FFMPG WASM library. I'm going to keep an eye out but to my understanding, trying to get a whole movie into 8MB just causes FFMPG to break. I'm not sure this is something I can solve :(

Even if it did work, trying to get a whole movie into the size of 2 songs would not yield great results lol!
